In [2]:
import numpy as np

In [3]:
# how to make an array in numpy
ar = np.array([1,2,3,4,5,6,7])
print(ar)

[1 2 3 4 5 6 7]


In [4]:
# to access a value of a index
ar[5]

6

In [5]:
print(ar[5])
ar[5]

6


6

In [6]:
print(type(ar))

<class 'numpy.ndarray'>


In [7]:
# to know the dimension of the array
print(ar.ndim)

1


In [8]:
# to know the datatype of the ar
print(ar.dtype)

int64


In [9]:
ar=np.array([1,2,3,4,5,6.5])
print(ar.dtype)
print(ar)

float64
[1.  2.  3.  4.  5.  6.5]


In [10]:
# we can define the datatype ourself also
ar = np.array([1,2,3,4,5,6.5], dtype="int32")
print(ar)
print(ar.dtype)

[1 2 3 4 5 6]
int32


In [11]:
print(ar.itemsize)

4


In [12]:
# numpy is fast than python because in the background some part of numpy is written in c so it is fast
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
%time a.sum()
# this tells us the time time taken to do the sum of all the elements in the array

CPU times: user 58 µs, sys: 9 µs, total: 67 µs
Wall time: 69.1 µs


4950

In [14]:
%timeit sum(a)
# so this is done in python and the time taken by it is much larger than the numpy

100000 loops, best of 5: 17.9 µs per loop


In [15]:
# slicing
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ar[3:7]

In [16]:
ar[3:7]

array([3, 4, 5, 6])

In [17]:
b = ar[3:7] 
# this is shallow copy
b

array([3, 4, 5, 6])

In [18]:
b[1]=1000
print(b)
print(ar)

[   3 1000    5    6]
[   0    1    2    3 1000    5    6    7    8    9]


In [19]:
cr = ar[2:7].copy()
cr 

array([   2,    3, 1000,    5,    6])

In [20]:
cr[1]=2000
print(cr)
print(ar)
# this id deep copy

[   2 2000 1000    5    6]
[   0    1    2    3 1000    5    6    7    8    9]


In [21]:
# to create 2D arrays
ar2 = np.array([
                [1,2,3,4,5,6],
                [7,8,9,0,12,13],
                [12,15,67,85,45,55]
])
print(ar2)
# in numpy we can create matrix only with same number of columns


[[ 1  2  3  4  5  6]
 [ 7  8  9  0 12 13]
 [12 15 67 85 45 55]]


In [22]:
print(type(ar2))
print(ar2.ndim)
print(ar2.shape)

<class 'numpy.ndarray'>
2
(3, 6)


In [23]:
ar2[1,2]

9

In [24]:
# slicing
print(ar2[1:3,0:3])
ar2

[[ 7  8  9]
 [12 15 67]]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9,  0, 12, 13],
       [12, 15, 67, 85, 45, 55]])

In [25]:
# split and concatenate
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10])
c = np.concatenate([a,b])
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
a1,a2, a3=np.split(a,[6,13])
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11 12]
[13 14 15 16 17 18 19]


In [30]:
# in 2D array there is hsplit, vsplit, dsplit
#  similarily in concatenate there is hconcatenate, vconcatenate, dconcatenate

ar2 = np.array([[1,2,3,4,5]])
br2 = np.array([[22,33,44,55,66],
                [111,222,333,444,555]
                ])

cr2 = np.concatenate([ar2,br2],axis=0)
cr2

array([[  1,   2,   3,   4,   5],
       [ 22,  33,  44,  55,  66],
       [111, 222, 333, 444, 555]])

In [32]:
a = np.ones(10)*5
a


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [33]:
b = np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
c = np.arange(0,100,5)
c

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [37]:
# Random function
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.random.permutation(a)

array([6, 5, 2, 8, 0, 9, 3, 4, 1, 7])

In [39]:
np.random.randn(2,10)

array([[ 1.49020273,  1.77167756, -2.53304339,  0.50446017, -0.07212174,
        -0.2207923 ,  1.61506156,  0.51279876,  0.46303157, -1.01774981],
       [ 0.11574942,  1.37437311,  1.71754114, -0.15337227, -0.54165413,
        -0.45852463,  0.17462608, -1.26046646,  0.77205046, -0.38896422]])

In [40]:
np.random.randint(2,10)

8

In [43]:
ar = np.linspace(5,100,50)
ar

array([  5.        ,   6.93877551,   8.87755102,  10.81632653,
        12.75510204,  14.69387755,  16.63265306,  18.57142857,
        20.51020408,  22.44897959,  24.3877551 ,  26.32653061,
        28.26530612,  30.20408163,  32.14285714,  34.08163265,
        36.02040816,  37.95918367,  39.89795918,  41.83673469,
        43.7755102 ,  45.71428571,  47.65306122,  49.59183673,
        51.53061224,  53.46938776,  55.40816327,  57.34693878,
        59.28571429,  61.2244898 ,  63.16326531,  65.10204082,
        67.04081633,  68.97959184,  70.91836735,  72.85714286,
        74.79591837,  76.73469388,  78.67346939,  80.6122449 ,
        82.55102041,  84.48979592,  86.42857143,  88.36734694,
        90.30612245,  92.24489796,  94.18367347,  96.12244898,
        98.06122449, 100.        ])

In [44]:
ar[32]-ar[31]

1.9387755102040671

In [45]:
ar[45]-ar[44]

1.9387755102040813

In [47]:
# reshape
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [49]:
a2 = a.reshape(2,25)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [50]:
np.where([True,False,True,True,False],1,0)

array([1, 0, 1, 1, 0])

In [51]:
# operators
a = np.arange(5)
b = np.arange(5)*2

In [52]:
a

array([0, 1, 2, 3, 4])

In [53]:
b

array([0, 2, 4, 6, 8])

In [54]:
print(a*b)

[ 0  2  8 18 32]


In [55]:
print(a+b)

[ 0  3  6  9 12]


In [56]:
print(a-b)

[ 0 -1 -2 -3 -4]


In [58]:
a[(a<=3)]

array([0, 1, 2, 3])

In [61]:
a=np.arange(20)
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [62]:
# Features
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
ar = np.array([2,45,2,5,6,3,9])
ar

array([ 2, 45,  2,  5,  6,  3,  9])

In [65]:
ar.sort()
ar

array([ 2,  2,  3,  5,  6,  9, 45])

In [66]:
print(ar.min())
print(ar.max())
print(ar.mean())
print(ar.sum())
print(ar.std())


2
45
10.285714285714286
72
14.359807855004643
